name: Docker Image CI
on:
  release:
    types: [published]

jobs:
  buildDocker:
    name: Build and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u simularium --password-stdin
      - name: Get the release tag
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the Docker image with tag
        run: docker build . --file Dockerfile --tag simularium/cytosim:${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        run: docker push simularium/cytosim:${{steps.vars.outputs.tag}}
      - name: Tag as the latest Docker image
        run: docker tag simularium/cytosim:${{steps.vars.outputs.tag}} simularium/cytosim:latest
      - name: Push the latest Docker image
        run: docker push simularium/cytosim:latest